CREATE TABLE Cars(ID BIGINT PRIMARY KEY AUTO_INCREMENT,
                  NAME VARCHAR(100), PRICE INT);

CREATE TABLE Boletos(ID UUID DEFAULT random_uuid(),
                  DUE_DATE DATE, TOTAL_IN_CENTS DECIMAL(17,2),
                  CUSTOMER VARCHAR (200), STATUS VARCHAR(10),
                  PAYMENT_DATE DATE);